name: "Residential"
version: '2025.5.1.0-SNAPSHOT'
main: me.blueb.residential.Residential
paper-plugin-loader: me.blueb.residential.ResidentialPluginLoader
api-version: '1.21'
load: STARTUP
authors: [ blueb ]

softdepend:
  - CMIEInjector
  - EssentialsX
depend:
  - Vault
