name: "Residential"
version: '2025.7.1.0-SNAPSHOT'
main: site.remlit.blueb.residential.Residential
paper-plugin-loader: site.remlit.blueb.residential.ResidentialPluginLoader
api-version: '1.20'
authors:
  - blueb

depend:
  - Vault
softdepend:
  - PlaceholderAPI
